apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2 # You might want more replicas for frontend to handle load
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      name: react-frontend
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: your-registry.com/react-frontend:latest # Replace with your image path
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
