version: '3.8'
services:
  backend:
    image: 'back:0.0.1'
    build:
      context: ./backend
    container_name: drive-back
    depends_on:
      - db
    networks:
      - main-network
    environment:
    - MONGO_DB_HOSTNAME=$MONGO_DB_HOSTNAME
    - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
    - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
    - MONGO_DB_PORT=$MONGO_DB_PORT
    - MONGO_DB_NAME=$MONGO_DB_NAME
    - allowedHost1=$allowedHost1
    - allowedHost2=$allowedHost2
    volumes:
      - ./backend/uploads:/usr/app/uploads
    ports:
      - '8080:8080'
  frontend:
    # https://mindsers.blog/post/https-using-nginx-certbot-docker/
    image: 'front:0.0.1'
    build:
      context: ./frontend
      args: 
          - BACKEND_URL=$BACKEND_URL 
    container_name: drive-front
    depends_on:
      - backend
    networks:
      - main-network
    ports:
      - '3000:80'
  db:
    image: mongo:latest
    environment:
    - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
    - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
    - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
      - main-network
    ports:
      - $DB_PORT

networks:
  main-network:
    name: $NETWORK_NAME

volumes:
  mongodb:
    driver: local