version: '3.8'
services:
  backend:
    image: 'back:0.0.1'
    build:
      context: ./backend
    container_name: drive-back
    depends_on:
      - db
    networks:
      - drive-networks
    environment:
      - MONGO_DB_HOSTNAME=db
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=admin
      - MONGO_DB_NAME=drive-clone
    volumes:
      - ./backend/uploads:/usr/app/uploads
    ports:
      - '8080:8080'
  # frontend:
  #   # https://mindsers.blog/post/https-using-nginx-certbot-docker/
  #   image: 'front:0.0.1'
  #   build:
  #     context: ./frontend
  #   container_name: drive-front
  #   depends_on:
  #     - backend
  #   networks:
  #     - drive-networks
  #   ports:
  #     - '3000:80'
  db:
    image: mongo:latest
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
      - drive-networks
    ports:
      - '27017:27017'

networks:
  drive-networks:
    driver: bridge

volumes:
  mongodb:
    driver: local