version: '3.8'
services:
  backend:
    image: 'back:0.0.1'
    build:
      context: ./drive-clone-backend
    container_name: drive-back    
    depends_on:
      - db
    networks:
      - main-network
    volumes:
      - ./drive-clone-backend/src/main/resources/static:/usr/app/static
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_NAME=$DB_NAME
      - DB_USER_USERNAME=$DB_USER_USERNAME
      - DB_PORT=$DB_PORT
      - DRIVE_USER_USERNAME=$DRIVE_USER_USERNAME
      - DRIVE_USER_PWD=$DRIVE_USER_PWD
      - DRIVE_USER_EMAIL=$DRIVE_USER_EMAIL
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_LEVEL_SECURITY=$LOG_LEVEL_SECURITY
      - ALLOWED_HOST=$ALLOWED_HOST
      - SERVER_PORT=$SERVER_PORT
  frontend:
    image: 'front:0.0.1'
    build:
      context: ./drive-clone-frontend
    container_name: drive-front
    depends_on:
      - backend
    networks:
      - main-network
    ports:
      - "$FRONTEND_PORT:80"
      - '443:443'
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro # mounting the folder to the nginx container 
      - ./certbot/data:/var/www/certbot
  db:
    restart: always
    networks:
      - main-network
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_USER_PASSWORD
      - POSTGRES_USER=$DB_USER_USERNAME
    ports:
      - "$DB_PORT:5432"
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - frontend
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt:rw
      - ./certbot/data:/var/www/certbot:rw

networks:
  main-network:
    name: $NETWORK_NAME

volumes:
  mongodb:
    driver: local
