version: '3.8'
services:
  backend:
    image: 'back:0.0.1'
    build:
      context: ./backend
    container_name: drive-back    
    depends_on:
      - db
    networks:
      - main-network
    volumes:
      - ./backend/uploads:/usr/app/uploads
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    environment:
      - MONGODB_URI=$MONGODB_URI
      - DB_NAME=$DB_NAME
      - USERNAME=$USERNAME
      - PWD=$PWD
      - ALLOWED_HOST=$ALLOWED_HOST
      - SERVER_PORT=$SERVER_PORT
  frontend:
    image: 'front:0.0.1'
    build:
      context: ./frontend
    container_name: drive-front
    depends_on:
      - backend
    networks:
      - main-network
    ports:
      - "80:80"
      - '443:443'
    volumes:
      - ../etc/nginx/templates:/etc/nginx/templates:ro
      - ../etc/letsencrypt:/etc/letsencrypt:ro # mounting the folder to the nginx container 
      - ../certbot/data:/var/www/certbot
  db:
    image: mongo:latest
    environment:
    - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
    - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
      - main-network
    ports:
      - "$DB_PORT:27017"
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - frontend
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt:rw
      - ./certbot/data:/var/www/certbot:rw

networks:
  main-network:
    name: $NETWORK_NAME

volumes:
  mongodb:
    driver: local
