version: '3.8'
services:
  backend:
    image: 'back:0.0.1'
    build:
      context: ./backend
    container_name: drive-back
    depends_on:
      - db
    networks:
      - $NETWORK_NAME
    env_file:
    - .env
    volumes:
      - ./backend/uploads:/usr/app/uploads
    ports:
      - '8080:8080'
  frontend:
    # https://mindsers.blog/post/https-using-nginx-certbot-docker/
    image: 'front:0.0.1'
    build:
      context: ./frontend
    container_name: drive-front

    depends_on:
      - backend
    networks:
      - $NETWORK_NAME
    ports:
      - '3000:80'
  db:
    image: mongo:latest
    env_file: 
    - .env
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
      - $NETWORK_NAME
    ports:
      - $DB_PORT

networks:
  $NETWORK_NAME:
    driver: bridge

volumes:
  mongodb:
    driver: local