version: '3.8'
services:
  backend:
    image: 'back:0.0.1'
    build:
      context: ./drive-clone-backend
    container_name: drive-back
    depends_on:
      - db
    networks:
      - main-network
    volumes:
      - ./drive-clone-backend/src/main/resources/static:/usr/app/static
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DRIVE_USER_USERNAME=$DRIVE_USER_USERNAME
      - DRIVE_USER_PWD=$DRIVE_USER_PWD
      - DRIVE_USER_EMAIL=$DRIVE_USER_EMAIL
      - LOG_LEVEL=$LOG_LEVEL
      - LOG_LEVEL_SECURITY=$LOG_LEVEL_SECURITY
      - ALLOWED_HOST=$ALLOWED_HOST
      - SERVER_PORT=$SERVER_PORT
      - SPRING_DATASOURCE_URL=jdbc:postgresql://drive-db/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USER_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_USER_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    restart: always
    container_name: drive-db
    networks:
      - main-network
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_USER_PASSWORD
      - POSTGRES_USER=$DB_USER_USERNAME
    ports:
      - "$DB_PORT:5432"
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - frontend
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email ${EMAIL} --agree-tos --no-eff-email
      -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt:rw
      - ./certbot/data:/var/www/certbot:rw
  frontend:
    image: 'front:0.0.1'
    build:
      context: ./drive-clone-frontend
    container_name: drive-front
    networks:
      - main-network
    ports:
      - "$FRONTEND_PORT:80"
      - "443:443"
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro # mounting the folder to the nginx container
      - ./certbot/data:/var/www/certbot

networks:
  main-network:
    name: $NETWORK_NAME
